name: Debug

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-package:
    # trunk-ignore(actionlint/runner-label)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: debug
        run: |
          ls -la
